### ISSUE TITLE
version 0.0.8 error - fview.index

### ISSUE THREAD

**Issue by ganySA** [gadicc/fview-flex#14]
Hi

Gettings the following error after upgrading to 0.0.8:

```
TypeError: fview.index is not a function
    at null.<anonymous> (famo.js?5b15e0bd199767c99f7e4e1e275e2891b2da3fa6:6)
    at view.js:191
    at Function.Template._withTemplateInstanceFunc (template.js:437)
    at view.js:190
    at Object.Blaze._withCurrentView (view.js:523)
    at viewAutorun (view.js:189)
    at Tracker.Computation._compute (tracker.js:341)
    at new Tracker.Computation (tracker.js:229)
    at Object.Tracker.autorun (tracker.js:580)
    at Blaze.View.autorun (view.js:201)
```

The layout looks like this:

```
<template name="listview">
    {{#ContainerSurface id="listings" translate=[0,0,100]}}

        {{#FlexLayoutController  layout='HeaderFooterLayout' layoutOptions=flcOps}}
            {{#Surface target="header" size="[undefined, 30]" translate=[0,0,150]}}
                <div style="background:#1e88e5; color: white;height: 35px;line-height: 35px;text-align:center;z-index:99999">{{name}}</div>
            {{/Surface}}

            {{#FlexScrollView layout="ListLayout" layoutOptions=fsvOps useContainer="true" flow="true" mouseMove="true" id="lf" target="content" alwaysLayout="true"}}
                {{#famousEach listings}}
                     {{>Surface template="listItem" size="[undefined,true]"}}
                {{/famousEach}}
            {{/FlexScrollView}}
        {{/FlexLayoutController}}
    {{/ContainerSurface}}

</template>
```

Will dig deeper when i get a chance....

**Comment by gadicc** [comment]
oops, had meant to cc you on the commit (I think you're the only one already using this)... `index()` got renamed to `selectedTab()`.  in general though try keep an eye on the History.md between upgrades.  you can also just look at the commit (https://github.com/gadicc/fview-flex/commit/aae45f4b8ef0a2dcb6a64aaae55e1bbfe2c8aab6) and look at demo.jade, demo.js etc to see how the demo code was changed, and/or see http://fview-flex.meteor.com/TabBar.  there might have been one or two other things, I added an _onRender shortcut in the latest famous-views preview.

**Comment by gadicc** [comment]
oh wait but you're not even using #TabBar in the code above.... is it in one of the includes maybe?  I didn't change anything else in that release so it must be that somewhere :>

**Comment by ganySA** [comment]
Hi Gadicc

Yes index renamed to selectedTab() worked perfectly!

Thanks. Will check the readme next time.
